name: PyTest & Flake8

on: [pull_request]

jobs:
  test-and-qa:
    name: Operating System - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest", "macos-latest" ]
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: spectro-dp
        environment-file: environment.yml
        auto-activate-base: false
    - name: Install development dependencies
      run: |
        conda env update --file environment_dev.yml
    - name: Install package
      run: |
        pip install -e .
    - name: Test with pytest
      run: |
        pytest tests/
    - name: Lint with flake8
      run: |
        flake8 . --count --show-source --statistics